package com.junhee.java.exception;

public class ExceptionMain {

	public static void main(String[] args) {

		// 예외 처리 try-catch;
		// 에러가 발생했을 때, 프로그램이 다운되지 말고 계속 실행하기 위해 사용하는 클래스.
		//

		try {
			// 실행시킬 로직 작성
			int array[] = new int[6];
			
			array[0] = 31;
			array[5] = 10;
			// 에러가 발생하더라도 결과값을 리턴해야한다.
			array[6] = 11;
			//
			int x = 1/0;

			// (예외 종류 이름 e) >
		} catch (ArrayIndexOutOfBoundsException nameOfException) {
			nameOfException.printStackTrace();

		} finally {
			
			System.out.println("다섯 번째 값 ="  );
		}
		System.out.println("시스템이 완료되었습니다.");
	}
}
